[package]
name = "blisp-repl"
version = "0.2.0"
authors = ["Yuuki Takano <ytakanoster@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blisp = { git = "https://github.com/ytakano/blisp.git" }
rustyline = "7.1.0"